# updatejava.yml
---
- name: Update Package on Debian system
  hosts: all
  become: yes  # Apply sudo privileges globally
  become_user: root  # Run tasks as the root user
  vars:
    ansible_python_interpreter: /usr/bin/python3.10

  tasks:
    - name: Run the equivalent of "apt-get update" as a separate step
      become: yes  # Explicitly escalate privileges for this task
      apt:
        update_cache: yes

    - name: Install the latest version of "openjdk-6-jdk"
      become: yes  # Explicit privilege escalation for installation
      apt:
        name: openjdk-6-jdk
        state: latest
        install_recommends: no
